### ISSUE TITLE
Export: PDF contains filter settings, but PNG doesn't

### ISSUE THREAD

**Issue by CroniD** [leanix/leanix-reporting#10]
I can't give you specfic examples, here, but I can provide them in private via mail (michael.szwarc@incowia.com).

Best regards

**Comment by psurrey** [comment]
Thank you @CroniD for creating this issue.

This works as intended.
We could add a checkbox to the export modal that allows the user to specify whether filters should be rendered into the PNG or not. But at the moment there is no urgency to implement this feature.
