### ISSUE TITLE
CustomDropdown.entries

### ISSUE THREAD

**Issue by CroniD** [leanix/leanix-reporting#3]
Hi there,

CustomDropdown.entries doesn't allow an empty array, null or undefined, which leads to an error.

Expected: it should handle an empty array, null and undefined without any errors.

Best regards

**Comment by psurrey** [comment]
Hi @CroniD ,

thank you for creating this bug report.
The issue is within the reporting framework in LeanIX itself and will be fixed with the next release.

Best regards
